// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlBLTk_sUQZENUWol1Fdx7kEm4Jh4XoM',
    appId: '1:84497181841:web:98e8d863e39b0621c82330',
    messagingSenderId: '84497181841',
    projectId: 'churrascaria-mobile',
    authDomain: 'churrascaria-mobile.firebaseapp.com',
    databaseURL: 'https://churrascaria-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'churrascaria-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9a3TaK7x6lQznqZxT0LGnjTX3S2ouqC8',
    appId: '1:84497181841:android:76db8140c136e915c82330',
    messagingSenderId: '84497181841',
    projectId: 'churrascaria-mobile',
    databaseURL: 'https://churrascaria-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'churrascaria-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIKCYEoteVhvOeB67fiqsIS3Yu9Ec8A0',
    appId: '1:84497181841:ios:2223758d7cd76c06c82330',
    messagingSenderId: '84497181841',
    projectId: 'churrascaria-mobile',
    databaseURL: 'https://churrascaria-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'churrascaria-mobile.appspot.com',
    iosClientId: '84497181841-s45s3k1q8j28a6q6tqksa66tjvgqlt5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIKCYEoteVhvOeB67fiqsIS3Yu9Ec8A0',
    appId: '1:84497181841:ios:ce86968ef2f03ae9c82330',
    messagingSenderId: '84497181841',
    projectId: 'churrascaria-mobile',
    databaseURL: 'https://churrascaria-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'churrascaria-mobile.appspot.com',
    iosClientId: '84497181841-11o1gudtpn6vheuvedpibqghjrlf3v9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoMobile.RunnerTests',
  );
}
